### ISSUE TITLE
Team Kermits-126

### ISSUE THREAD

**Issue by Srjnnnn** [defoebrand/Tracker-Keeper#1]
- For the type of input, you can make it a select menu.
- It looks great, good job.
- A preview for the uploaded picture would be a nice idea.
- An error display for the empty 'name of transaction' menu would be good.
- Eliminating the whitespace from the user name would be a good idea.

**Comment by defoebrand** [comment]
Input has been made a select menu
A profile pic preview is presently beyond the scope of my abilities in jQuery but is accounted for in upcoming features
Error display for transaction has been fixed
Whitespace in usernames is eliminated from outermost input and minimum char length enacted
